springfox:
 documentation:
  swagger:
   v2:
    path: /api-docs
    
server:
  contextPath: /hero-api
  por: 8080


endpoints:
  health:
    enabled: false
###
#   Database Settings
###
spring:
 jackson: 
  date-format: com.pdy.fac.demorestback.RFC3339DateFormat
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
 datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    plaform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
# Hibernate va charger import.sql
# c'est la datasource spring qui s'occupe d'initialiser
    initialize: true
 jpa:
  hibernate:
   dll-auto: none
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
   hibernate:
    show_sql: false
    use_sql_comment: false
    format_sql: false
 h2:
  console:
    enabled: true
    path: /console
    settings:
     trace: false
     web-allow-others: false

     
info:
  build:
   artifact: '@project.artifactId@'
   name: '@project.name@'
   description: '@project.description@'
   version: '@project.version@'     